import React from 'react';
import { Text, View } from 'react-native';
import { Card, EntityCard, MetricTile, QueryState, RefreshingScrollView, Screen, ScreenHeader, SectionHeader } from '@/design/components';
import { useTheme } from '@/design/theme';
import { formatShortDate, formatZar } from '@/data/format';
import { useAccounting } from '@/features/portfolio/usePortfolioData';
import { useAuth } from '@/features/auth/AuthProvider';
import { PermissionMessage } from '@/features/portfolio/PortfolioPrimitives';

export default function AccountingScreen() {
  const { spacing, color, typeScale } = useTheme(); const { session } = useAuth(); const query = useAccounting(); const data = query.data;
  if (!session?.user.capabilities.canViewFinancials) return <Screen><ScreenHeader title="Accounting" /><View style={{ padding: spacing[5] }}><PermissionMessage message="Financial information is only shown when the server grants financial access." /></View></Screen>;
  return <Screen><ScreenHeader title="Accounting" subtitle="August 2026 portfolio overview" /><QueryState isLoading={query.isLoading} error={query.error} isEmpty={!data} emptyTitle="No financial activity" emptyDescription="Transactions will appear after the first rent or expense is recorded." onRetry={query.reload}>{data ? <RefreshingScrollView refreshing={query.isRefreshing} onRefresh={query.reload} contentContainerStyle={{ paddingHorizontal: spacing[5], paddingBottom: 110 }}><View style={{ flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: spacing[3] }}><MetricTile label="Rent received" value={formatZar(data.rentReceived)} detail="This month" tone="success" /><MetricTile label="Outstanding" value={formatZar(data.outstandingRent)} detail="Needs follow-up" tone="danger" /><MetricTile label="Expenses" value={formatZar(data.expenses)} detail="Cleared & pending" tone="warning" /><MetricTile label="Net income" value={formatZar(data.netIncome)} detail="Before distributions" tone="info" /></View><SectionHeader title="Reconciliation" /><Card><Text style={[typeScale.title, { color: color.textPrimary }]}>{data.unreconciledCount}</Text><Text style={[typeScale.caption, { color: color.textSecondary, marginTop: spacing[1] }]}>transactions need matching</Text><Text style={[typeScale.micro, { color: color.textMuted, marginTop: spacing[3] }]}>Bank-feed reconciliation requires backend integration and is not active in this frontend preview.</Text></Card><SectionHeader title="Financial activity" />{data.transactions.map((item) => <View key={item.id} style={{ marginBottom: spacing[3] }}><EntityCard title={item.label} subtitle={`${item.propertyName} · ${formatShortDate(item.occurredAt)}`} detail={`${item.direction === 'expense' || item.direction === 'distribution' ? '−' : '+'}${formatZar(item.amount)}`} icon="money" status={item.status} statusTone={item.status === 'overdue' ? 'danger' : item.status === 'pending' ? 'warning' : 'success'} /></View>)}</RefreshingScrollView> : null}</QueryState></Screen>;
}
