import type { MetadataRoute } from 'next';
import { branding } from '@propvault/config';

// Stage 5 (commercial-launch execution plan, WORKLOG.md 2026-08-06) -- PWA installability.
// Next.js's manifest.ts file convention generates /manifest.webmanifest and auto-injects the
// <link rel="manifest"> tag; no additional wiring needed in app/layout.tsx for this file alone.
// start_url is /dashboard (not '/', which redirects unauthenticated visitors to /login) so an
// installed icon reopens straight into the app for an already-signed-in user, matching how the
// (dashboard) route group's own middleware already treats '/' as a redirect-only entry point.
//
// Icons are static files (public/icons/*, generated by scripts/make-icons.mjs from the real
// Proplyst logo, branding/proplyst-logo.png -- Stage 7 rebrand, 2026-08-06), not the
// dynamically-generated placeholder badge this originally shipped with.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${branding.productName} — Property Governance Platform`,
    short_name: branding.productName,
    description:
      'Manage properties, tenants, owners, and finances — with shared ownership and governance built in.',
    start_url: '/dashboard',
    display: 'standalone',
    // Matches the icon set's own background (sampled from the logo, apps/admin/scripts/make-icons.mjs)
    // rather than white, so the OS splash screen shown before the app loads doesn't flash a
    // mismatched colour against the dark-navy icon.
    background_color: '#000615',
    theme_color: '#106ADD',
    icons: [
      { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
      { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
      {
        src: '/icons/icon-maskable-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
  };
}
