import React, { useState } from 'react';
import { Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useRepositories } from '@/data/RepositoryProvider';
import { useRepositoryQuery } from '@/data/useRepositoryQuery';
import { formatZar } from '@/data/format';
import { Card, Chip, ConfirmationSheet, EntityCard, PermissionGate, PrimaryButton, QueryState, RefreshingScrollView, Screen, ScreenHeader, SectionHeader, StatusPill } from '@/design/components';
import { useTheme } from '@/design/theme';
import { useAuth } from '@/features/auth/AuthProvider';
type PropertyTab = 'overview' | 'units' | 'finance' | 'documents';

export default function PropertyDetailScreen() {
  const { id = '' } = useLocalSearchParams<{ id: string }>(); const { color, spacing, typeScale } = useTheme(); const { session } = useAuth(); const repositories = useRepositories();
  const propertyQuery = useRepositoryQuery(() => repositories.properties.getById(id), [repositories.properties, id]); const unitsQuery = useRepositoryQuery(() => repositories.units.list(id), [repositories.units, id]);
  const documentsQuery = useRepositoryQuery(async () => (await repositories.documents.list()).filter((item) => item.linkedEntity.includes(propertyQuery.data?.nickname ?? '__none__')), [repositories.documents, propertyQuery.data?.nickname]);
  const [tab, setTab] = useState<PropertyTab>('overview'); const [archiveVisible, setArchiveVisible] = useState(false); const property = propertyQuery.data; const go = (path: string) => router.push(path as never);
  return <Screen><ScreenHeader title={property?.nickname ?? 'Property'} subtitle={property?.city} back action={session?.user.capabilities.canEditProperty && property ? { label: 'Edit', onPress: () => go(`/(app)/properties/${id}/edit`) } : undefined} /><QueryState isLoading={propertyQuery.isLoading} error={propertyQuery.error} isEmpty={!property} emptyTitle="Property unavailable" emptyDescription="This property may no longer be available to your account." onRetry={propertyQuery.reload}>{property ? <RefreshingScrollView refreshing={propertyQuery.isRefreshing} onRefresh={() => { void propertyQuery.reload(); void unitsQuery.reload(); void documentsQuery.reload(); }} contentContainerStyle={{ paddingHorizontal: spacing[5], paddingBottom: spacing[8] }}>
    <Card style={{ backgroundColor: '#071426', borderColor: '#183253', padding: spacing[5] }}><StatusPill label={property.propertyType.replace('_', ' ')} tone="info" /><Text style={[typeScale.title, { color: '#FFFFFF', marginTop: spacing[3] }]}>{property.nickname}</Text><Text style={[typeScale.body, { color: '#B9C7DA', marginTop: spacing[1] }]}>{property.fullAddress}</Text><View style={{ flexDirection: 'row', gap: spacing[3], marginTop: spacing[5] }}><HeroMetric label="Units" value={`${property.occupiedUnits}/${property.unitCount}`} /><HeroMetric label="Monthly rent" value={formatZar(property.monthlyRent, { compact: true })} /><HeroMetric label="Value" value={property.estimatedValue ? formatZar(property.estimatedValue, { compact: true }) : '—'} /></View></Card>
    <View style={{ flexDirection: 'row', gap: spacing[2], marginTop: spacing[4] }}>{(['overview', 'units', 'finance', 'documents'] as PropertyTab[]).map((item) => <Chip key={item} label={item[0]!.toUpperCase() + item.slice(1)} selected={tab === item} onPress={() => setTab(item)} />)}</View>
    {tab === 'overview' ? <><SectionHeader title="At a glance" /><View style={{ gap: spacing[3] }}><EntityCard title={property.occupiedUnits === property.unitCount ? 'Fully occupied' : `${property.unitCount - property.occupiedUnits} vacant units`} subtitle={`${property.occupiedUnits} of ${property.unitCount} units occupied`} icon="unit" status={property.occupiedUnits === property.unitCount ? 'Healthy' : 'Attention'} statusTone={property.occupiedUnits === property.unitCount ? 'success' : 'warning'} onPress={() => setTab('units')} /><EntityCard title={property.outstandingBalance > 0 ? `${formatZar(property.outstandingBalance)} outstanding` : 'No outstanding rent'} subtitle="Current tenant balances" icon="money" status={property.outstandingBalance > 0 ? 'Review' : 'Clear'} statusTone={property.outstandingBalance > 0 ? 'danger' : 'success'} onPress={() => setTab('finance')} /><EntityCard title="Maintenance" subtitle="Open requests and recent work" icon="maintenance" onPress={() => go('/(app)/maintenance')} /></View><SectionHeader title="Ownership & records" /><Card><Info label="Municipal account" value={property.municipalAccountNumber ?? 'Not added'} /><Info label="Ownership" value="2 registered owners" /><Info label="Notes" value={property.notes ?? 'No notes'} last /></Card><PermissionGate allowed={Boolean(session?.user.capabilities.canEditProperty)}><View style={{ marginTop: spacing[5], gap: spacing[3] }}><PrimaryButton label="Manage property photos" variant="secondary" onPress={() => go(`/(app)/properties/${id}/photos`)} /><PrimaryButton label="Archive property" variant="secondary" onPress={() => setArchiveVisible(true)} /></View></PermissionGate></> : null}
    {tab === 'units' ? <><SectionHeader title="Units" actionLabel="View all" onAction={() => go(`/(app)/units?propertyId=${id}`)} /><QueryState isLoading={unitsQuery.isLoading} error={unitsQuery.error} isEmpty={!unitsQuery.data?.length} emptyTitle="No units" emptyDescription="Units added to this property will appear here." onRetry={unitsQuery.reload}><View style={{ gap: spacing[3] }}>{unitsQuery.data?.map((unit) => <EntityCard key={unit.id} title={unit.name} subtitle={unit.tenantName ?? 'Vacant'} detail={`${unit.bedrooms} bed · ${formatZar(unit.monthlyRent)}/month`} icon="unit" status={unit.occupancy} statusTone={unit.occupancy === 'occupied' ? 'success' : 'warning'} onPress={() => go(`/(app)/units/${unit.id}`)} />)}</View></QueryState></> : null}
    {tab === 'finance' ? <><SectionHeader title="Financial summary" />{session?.user.capabilities.canViewFinancials ? <Card><Info label="Monthly rent roll" value={formatZar(property.monthlyRent)} /><Info label="Outstanding balance" value={formatZar(property.outstandingBalance)} tone={property.outstandingBalance > 0 ? color.danger : color.statusPaid} /><Info label="Estimated value" value={property.estimatedValue ? formatZar(property.estimatedValue) : 'Not recorded'} last /></Card> : <Card><Text style={[typeScale.body, { color: color.textSecondary }]}>Financial access is restricted for this account.</Text></Card>}</> : null}
    {tab === 'documents' ? <><SectionHeader title="Property documents" actionLabel="Upload" onAction={() => go('/(app)/documents/upload')} /><QueryState isLoading={documentsQuery.isLoading} error={documentsQuery.error} isEmpty={!documentsQuery.data?.length} emptyTitle="No linked documents" emptyDescription="Upload leases, statements and inspections." onRetry={documentsQuery.reload}><View style={{ gap: spacing[3] }}>{documentsQuery.data?.map((document) => <EntityCard key={document.id} title={document.title} subtitle={`${document.category} · ${document.sizeLabel}`} icon="document" status={document.status.replace('_', ' ')} statusTone={document.status === 'ready' ? 'success' : 'warning'} onPress={() => go(`/(app)/documents/${document.id}`)} />)}</View></QueryState></> : null}
  </RefreshingScrollView> : null}</QueryState><ConfirmationSheet visible={archiveVisible} title="Archive this property?" description="It will leave the active portfolio but no records are deleted." confirmLabel="Archive" destructive onCancel={() => setArchiveVisible(false)} onConfirm={async () => { await repositories.properties.archive(id); setArchiveVisible(false); router.back(); }} /></Screen>;
  function HeroMetric({ label, value }: { label: string; value: string }) { return <View style={{ flex: 1 }}><Text style={[typeScale.micro, { color: '#8FA5BF' }]}>{label}</Text><Text style={[typeScale.heading, { color: '#FFFFFF', marginTop: 2 }]}>{value}</Text></View>; }
  function Info({ label, value, tone, last }: { label: string; value: string; tone?: string; last?: boolean }) { return <View style={{ paddingVertical: spacing[3], borderBottomWidth: last ? 0 : 1, borderBottomColor: color.border }}><Text style={[typeScale.caption, { color: color.textMuted }]}>{label}</Text><Text style={[typeScale.body, { color: tone ?? color.textPrimary, marginTop: 2, fontWeight: '600' }]}>{value}</Text></View>; }
}
