import React from 'react';
import { Pressable, Text, View } from 'react-native';
import { router } from 'expo-router';
import { useAuth } from '@/features/auth/AuthProvider';
import { useRepositories } from '@/data/RepositoryProvider';
import { useRepositoryQuery } from '@/data/useRepositoryQuery';
import { relativeTime } from '@/data/format';
import { AppIcon, Card, DemoBadge, EntityCard, MetricTile, PermissionGate, QueryState, RefreshingScrollView, Screen, SectionHeader, StatusPill } from '@/design/components';
import { useTheme } from '@/design/theme';

export default function DashboardScreen() {
  const { color, radii, spacing, typeScale } = useTheme();
  const { session } = useAuth();
  const { dashboard } = useRepositories();
  const query = useRepositoryQuery(() => dashboard.getSnapshot(), [dashboard]);
  const capabilities = session?.user.capabilities;
  return <Screen><RefreshingScrollView refreshing={query.isRefreshing} onRefresh={query.reload} contentContainerStyle={{ padding: spacing[5], paddingBottom: spacing[8] }}>
    <View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }}><View style={{ flex: 1 }}><Text style={[typeScale.caption, { color: color.textSecondary }]}>Good morning</Text><Text style={[typeScale.title, { color: color.textPrimary, marginTop: 2 }]}>{session?.user.firstName || 'Welcome'}</Text><Text style={[typeScale.caption, { color: color.textMuted, marginTop: 2 }]}>{session?.user.organizationName}</Text></View><View style={{ alignItems: 'flex-end', gap: spacing[2] }}><DemoBadge /><Pressable onPress={() => router.push('/(app)/notifications' as never)} accessibilityRole="button" accessibilityLabel="Open notifications" style={{ width: 44, height: 44, borderRadius: 22, backgroundColor: color.surfaceRaised, borderWidth: 1, borderColor: color.border, alignItems: 'center', justifyContent: 'center' }}><AppIcon name="notification" color={color.accent} /></Pressable></View></View>
    <QueryState isLoading={query.isLoading} error={query.error} isEmpty={!query.data} emptyTitle="No dashboard yet" emptyDescription="Portfolio information will appear here once available." onRetry={query.reload}>{query.data ? <>
      <Card style={{ marginTop: spacing[5], backgroundColor: '#071426', borderColor: '#183253', padding: spacing[5] }}><StatusPill label="Live portfolio overview" tone="info" /><Text style={[typeScale.caption, { color: '#A9BAD0', marginTop: spacing[4] }]}>{query.data.portfolioLabel}</Text><Text style={[typeScale.display, { color: '#FFFFFF', marginTop: spacing[1] }]}>{query.data.portfolioValue}</Text><View style={{ flexDirection: 'row', gap: spacing[2], marginTop: spacing[4] }}><QuickAction label="Add property" icon="add" onPress={() => router.push('/(app)/properties/add')} /><PermissionGate allowed={Boolean(capabilities?.canUploadDocuments)}><QuickAction label="Upload" icon="upload" onPress={() => router.push('/(app)/documents/upload' as never)} /></PermissionGate></View></Card>
      <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: spacing[3], marginTop: spacing[4] }}>{query.data.metrics.map((metric) => <MetricTile key={metric.id} {...metric} />)}</View>
      <SectionHeader title="Needs attention" /><View style={{ gap: spacing[3] }}><EntityCard title={`${query.data.maintenanceAttention} maintenance items`} subtitle="Urgent and high-priority requests" icon="maintenance" status="Review" statusTone="danger" onPress={() => router.push('/(app)/maintenance' as never)} /><EntityCard title={`${query.data.leaseExpiries} lease expiries`} subtitle="Due within the next 60 days" icon="lease" status="Upcoming" statusTone="warning" onPress={() => router.push('/(app)/leases' as never)} /></View>
      <SectionHeader title="Tasks & reminders" /><Card>{query.data.tasks.map((task, index) => <Pressable key={task.id} onPress={() => task.destination && router.push(task.destination as never)} accessibilityRole="button" style={{ flexDirection: 'row', gap: spacing[3], paddingVertical: spacing[3], borderBottomWidth: index === query.data!.tasks.length - 1 ? 0 : 1, borderBottomColor: color.border }}><View style={{ width: 28, height: 28, borderRadius: radii.pill, backgroundColor: color.accentSoft, alignItems: 'center', justifyContent: 'center' }}><AppIcon name="check" size={14} color={color.accent} /></View><View style={{ flex: 1 }}><Text style={[typeScale.body, { color: color.textPrimary, fontWeight: '700' }]}>{task.title}</Text><Text style={[typeScale.caption, { color: color.textSecondary }]}>{task.detail}</Text></View></Pressable>)}</Card>
      <SectionHeader title="Recent activity" actionLabel="View all" onAction={() => router.push('/(app)/notifications' as never)} /><Card>{query.data.recentActivity.map((activity, index) => <View key={activity.id} style={{ flexDirection: 'row', gap: spacing[3], paddingVertical: spacing[3], borderBottomWidth: index === query.data!.recentActivity.length - 1 ? 0 : 1, borderBottomColor: color.border }}><View style={{ width: 8, height: 8, marginTop: 7, borderRadius: 4, backgroundColor: color.accent }} /><View style={{ flex: 1 }}><Text style={[typeScale.body, { color: color.textPrimary, fontWeight: '600' }]}>{activity.title}</Text><Text style={[typeScale.caption, { color: color.textSecondary }]}>{activity.detail}</Text></View><Text style={[typeScale.micro, { color: color.textMuted }]}>{relativeTime(activity.occurredAt)}</Text></View>)}</Card>
      <SectionHeader title="Notices" />{query.data.notices.map((notice) => <Card key={notice.id} style={{ backgroundColor: color.accentSoft, marginBottom: spacing[3] }}><Text style={[typeScale.body, { color: color.textPrimary, fontWeight: '700' }]}>{notice.title}</Text><Text style={[typeScale.caption, { color: color.textSecondary, marginTop: spacing[1] }]}>{notice.detail}</Text></Card>)}
    </> : null}</QueryState>
  </RefreshingScrollView></Screen>;

  function QuickAction({ label, icon, onPress }: { label: string; icon: 'add' | 'upload'; onPress: () => void }) { return <Pressable onPress={onPress} accessibilityRole="button" style={({ pressed }) => ({ flex: 1, minHeight: 48, borderRadius: radii.lg, backgroundColor: pressed ? '#1D3C60' : '#132B48', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing[2] })}><AppIcon name={icon} color="#FFFFFF" /><Text style={[typeScale.caption, { color: '#FFFFFF', fontWeight: '700' }]}>{label}</Text></Pressable>; }
}
